### ISSUE TITLE
App crashes instantly 

### ISSUE THREAD

**Issue by pacjo** [FazziCLAY/OpenToday#1]
Hi, I found your app on fdroid and I wanted to give it a try. Sadly it crashes every time I open it.

Clearing cashe or force stopping doesn't change anything.

Some information:
OS: Android 12, crDroid 8.9 (latest security patch)
Device: Redmi Note 10 Pro

Logs:
```
=== OpenToday Crash ===
CrashID: 93d1b34c-7b6c-4351-aa18-c9435083349b
Application: (ru.fazziclay.opentoday)
 * VERSION_BUILD: 52
 * VERSION_NAME: 0.9.3 (build 52)
 * DATA_VERSION: 5
 * DEBUG: false
 * DEBUG_TICK_NOTIFICATION: false
 * DEBUG_MAIN_ACTIVITY_START_SLEEP: 0
 * DEBUG_APP_START_SLEEP: 0
 * DEBUG_MAIN_ACTIVITY: null
 * DEBUG_TEST_EXCEPTION_ONCREATE_MAINACTIVITY: false

Device:
 * SDK_INT: 32
 * BASE_OS: 

Time:
* Formatted: 2022.10.03 18:47:50
* Millis: 1664815670153
* Nano: 2100527712790

Thread: Thread[main,5,main]
Throwable:
java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.fazziclay.opentoday/ru.fazziclay.opentoday.ui.activity.MainActivity}: java.lang.IllegalArgumentException: ru.fazziclay.opentoday: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3662)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3819)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:102)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2242)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7833)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.IllegalArgumentException: ru.fazziclay.opentoday: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
	at ru.fazziclay.opentoday.app.receiver.QuickNoteReceiver.sendQuickNoteNotification(QuickNoteReceiver.java:23)
	at ru.fazziclay.opentoday.ui.activity.MainActivity.sendQuickNoteNotify(MainActivity.java:71)
	at ru.fazziclay.opentoday.ui.activity.MainActivity.onCreate(MainActivity.java:67)
	at android.app.Activity.performCreate(Activity.java:8057)
	at android.app.Activity.performCreate(Activity.java:8037)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1347)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3643)
	... 12 more

--- OpenToday Crash ---

```

**Comment by pacjo** [comment]
Just updated to 0.9.5 and it's working fine now. Thanks.
